### ISSUE TITLE
Possible Cache problem when the network drops out. Stuck in a loop.

### ISSUE THREAD

**Issue by simonbrennan** [eResearchSA/reporting-producers#37]
Even though the code is meant to back off when the network is offline, it doesn't appear to work all that well. There is possibly something wrong with the caching mechanism. 

```
2015-11-16 11:51:51,417 - ERROR - Pusher-1 - MainThread - network or remote server error, back off for 1 seconds
Traceback (most recent call last):
  File "/opt/producers/reporting/pusher.py", line 99, in run
    self.client.push(data_list)
  File "/opt/producers/reporting/outputs.py", line 50, in push
    sub=data[0]['schema'].split('.')[0]
IndexError: list index out of range
2015-11-16 11:51:53,421 - ERROR - Pusher-1 - MainThread - unable to read file /var/lib/reporting-producer/cache/linux/d4f6b9e2-7511-4135-b05e-6170f3c6f971
Traceback (most recent call last):
  File "/opt/producers/reporting/pusher.py", line 91, in run
    dat

```

**Comment by Li-ReDBox** [comment]
No further report received. Close for now.
